# Generated by Django 5.0.6 on 2024-06-18 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('weight', 'Weight'), ('value', 'Value')], max_length=20)),
                ('condition', models.CharField(choices=[('lt', 'Less Than'), ('lte', 'Less Than or Equal To'), ('gt', 'Greater Than'), ('gte', 'Greater Than or Equal To'), ('eq', 'Equal To')], max_length=4)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sequence_id', models.PositiveIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.department')),
            ],
            options={
                'ordering': ['sequence_id'],
            },
        ),
    ]
