# Generated by Django 5.0.6 on 2024-06-18 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_user', to='departments.department')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_department', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
